// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CommandStatus.
const (
	Aborted    CommandStatus = "aborted"
	Crush      CommandStatus = "crush"
	Ended      CommandStatus = "ended"
	InProgress CommandStatus = "in_progress"
	New        CommandStatus = "new"
)

// Command defines model for Command.
type Command struct {
	BodyScript      string        `json:"body_script"`
	Id              int64         `json:"id"`
	ResultRunScript string        `json:"result_run_script"`
	Status          CommandStatus `json:"status"`
}

// CommandStatus defines model for Command.Status.
type CommandStatus string

// Commands defines model for Commands.
type Commands = []Command

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// StatusMessage defines model for StatusMessage.
type StatusMessage struct {
	Message string `json:"message"`
}

// CreateCommandJSONRequestBody defines body for CreateCommand for application/json ContentType.
type CreateCommandJSONRequestBody = Command

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /commands)
	GetCommands(w http.ResponseWriter, r *http.Request)
	// Создание и добавление команды
	// (POST /commands)
	CreateCommand(w http.ResponseWriter, r *http.Request)
	// Получение команды по идентификатору
	// (GET /commands/{command_id})
	ShowCommandById(w http.ResponseWriter, r *http.Request, commandId int64)
	// Запуск команды по идентификатору
	// (POST /commands/{command_id}/run)
	RunCommandById(w http.ResponseWriter, r *http.Request, commandId int64)
	// Остановка команды по идентификатору
	// (POST /commands/{command_id}/stop)
	StopCommandById(w http.ResponseWriter, r *http.Request, commandId int64)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCommands operation middleware
func (siw *ServerInterfaceWrapper) GetCommands(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCommands(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateCommand operation middleware
func (siw *ServerInterfaceWrapper) CreateCommand(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCommand(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ShowCommandById operation middleware
func (siw *ServerInterfaceWrapper) ShowCommandById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "command_id" -------------
	var commandId int64

	err = runtime.BindStyledParameter("simple", false, "command_id", mux.Vars(r)["command_id"], &commandId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "command_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ShowCommandById(w, r, commandId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RunCommandById operation middleware
func (siw *ServerInterfaceWrapper) RunCommandById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "command_id" -------------
	var commandId int64

	err = runtime.BindStyledParameter("simple", false, "command_id", mux.Vars(r)["command_id"], &commandId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "command_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunCommandById(w, r, commandId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// StopCommandById operation middleware
func (siw *ServerInterfaceWrapper) StopCommandById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "command_id" -------------
	var commandId int64

	err = runtime.BindStyledParameter("simple", false, "command_id", mux.Vars(r)["command_id"], &commandId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "command_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopCommandById(w, r, commandId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/commands", wrapper.GetCommands).Methods("GET")

	r.HandleFunc(options.BaseURL+"/commands", wrapper.CreateCommand).Methods("POST")

	r.HandleFunc(options.BaseURL+"/commands/{command_id}", wrapper.ShowCommandById).Methods("GET")

	r.HandleFunc(options.BaseURL+"/commands/{command_id}/run", wrapper.RunCommandById).Methods("POST")

	r.HandleFunc(options.BaseURL+"/commands/{command_id}/stop", wrapper.StopCommandById).Methods("POST")

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWQW/bNhT+K9rbjmrsNsMOOqYYhh52WXYbgoCRnm0WEcmRVDojMNAkA5Yhhx0H7NBh",
	"2GFXtUhQNZmcv/D4jwZSsh07TpssRrdDLgZlke9973vf+6h9SGWupEBhDST7YNIB5iwsn8o8ZyLzS6Wl",
	"Qm05hhc7Mhtum1RzZf2jHSqEBIzVXPRhFAMPZ3pS58xCAlzYLz6HeLKPC4t91H6jRlPs2m1diPeFM5bZ",
	"IiRGUeSQfAcCX0AMXGwrLfsajYEYUGSYQQypLswAYmA7UlvMYCtejBgSf19wjZkPxv2pqyUtwzVFMQsn",
	"d55jaj3AlqgAkVvMw+IzjT1I4NPOjN9OS25nwuxoGoxpzYb++Uutpb5OeSozXCR1/clSUnM0hvVxCZUL",
	"hYeYs/3LKtsMRX89iziP6tapbs7hd3LRkyEGt7v+3QYzg0cN8ZFBvYcaYthDbbgUkMDjte5a16OTCgVT",
	"HBJYX+uurUMMitlBQOZZn/akj0FYHjmzXIpnGSTwFdpp30LHlRSmKetJt9twLiyKcJQptcvTcLjz3HgU",
	"k0m5a8/N9aZ7CjJs6m0qpN9oTH9TSTWdupOIairpHZ3SGdXuBML2Hit27Z1Qvg9co7plSF65Y6roNZ1T",
	"GdEljSN6SyVdupc0dgfuKKLzGdQmgJJmCd1PNTKLE+E36kBjN2Q2XFkV07Gal5/VBY6utfjxytLOD8kH",
	"2kll5I7cAV3SmTum2hN6SmN6TSW9oQvfYSo/aocLgT8oTC1mEbZ7YjBFnjM99Nj/oDG99bipporOIqqu",
	"Iw7/n1/VrHcm1jeNzbTC3/KRp4PZ2W9X2zwb3TilmwP5om3rxvBZFkZcsxwtah98f6GYbwcY8SySvcgO",
	"MGoTRFZGGq3muIfh2oAkGAXEIFjuB3GGBBaFE1/h94M32mjrnk5ya3XPl/3fWgJduCP30w1CaE2jat3r",
	"kCr3I1X+rDuksXvpjhYF9/v9I95NfB1dBF6WG9c3hXgQ4C197s+ZsbkTeje5K7zfnf8LXXxMUf/l0z7y",
	"PwGZO6YLv6zpLHKHVHr8/tKr5mpagdp/vQ9Dd9S5sVLdLPRNK9WD0m+p9Enbfg4mVVPpfplrn7fGK19t",
	"VH7yf5WzN/BqRWJ+5Q5C9JrG9Ka5H1Yj6dHonwAAAP//3qdNzKgOAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
