// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.0.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
)

// Defines values for CommandStatus.
const (
	Aborted    CommandStatus = "aborted"
	Crush      CommandStatus = "crush"
	Ended      CommandStatus = "ended"
	InProgress CommandStatus = "in_progress"
	New        CommandStatus = "new"
)

// Command defines model for Command.
type Command struct {
	BodyScript      string        `json:"body_script"`
	Id              int64         `json:"id"`
	ResultRunScript string        `json:"result_run_script"`
	Status          CommandStatus `json:"status"`
}

// CommandStatus defines model for Command.Status.
type CommandStatus string

// Commands defines model for Commands.
type Commands = []Command

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// StatusMessage defines model for StatusMessage.
type StatusMessage struct {
	Message string `json:"message"`
}

// CreateCommandJSONRequestBody defines body for CreateCommand for application/json ContentType.
type CreateCommandJSONRequestBody = Command

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /commands)
	GetCommands(w http.ResponseWriter, r *http.Request)
	// Создание и добавление команды
	// (POST /commands)
	CreateCommand(w http.ResponseWriter, r *http.Request)
	// Получение команды по идентификатору
	// (GET /commands/{command_id})
	ShowCommandById(w http.ResponseWriter, r *http.Request, commandId string)
	// Запуск команды по идентификатору
	// (POST /commands/{command_id}/run)
	RunCommandById(w http.ResponseWriter, r *http.Request, commandId string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetCommands operation middleware
func (siw *ServerInterfaceWrapper) GetCommands(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCommands(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// CreateCommand operation middleware
func (siw *ServerInterfaceWrapper) CreateCommand(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCommand(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// ShowCommandById operation middleware
func (siw *ServerInterfaceWrapper) ShowCommandById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "command_id" -------------
	var commandId string

	err = runtime.BindStyledParameter("simple", false, "command_id", mux.Vars(r)["command_id"], &commandId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "command_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ShowCommandById(w, r, commandId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// RunCommandById operation middleware
func (siw *ServerInterfaceWrapper) RunCommandById(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "command_id" -------------
	var commandId string

	err = runtime.BindStyledParameter("simple", false, "command_id", mux.Vars(r)["command_id"], &commandId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "command_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RunCommandById(w, r, commandId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/commands", wrapper.GetCommands).Methods("GET")

	r.HandleFunc(options.BaseURL+"/commands", wrapper.CreateCommand).Methods("POST")

	r.HandleFunc(options.BaseURL+"/commands/{command_id}", wrapper.ShowCommandById).Methods("GET")

	r.HandleFunc(options.BaseURL+"/commands/{command_id}/run", wrapper.RunCommandById).Methods("POST")

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+RVzW7bRhB+FWLaIyMpcdEDjw6KIodemt4KQ1iTI2kDcZfdXToVBAGJVaAG/AAFemhR",
	"9NArU1iILFfyK8y+UbFLSrIk+q823EMuwlKcnfnmm28+DiGWaSYFCqMhGoKOe5gyf3wp05SJxB0zJTNU",
	"hqN/cSiTQVvHimfGPZpBhhCBNoqLLoxC4P5OR6qUGYiAC/PlFxAu47gw2EXlAhXqvG/aKhc3pdOGmdwX",
	"RpGnEH0PAt9CCFy0MyW7CrWGEFAkmEAIscp1D0Jgh1IZTOAg3M7oC/+Qc4WJS8bdrast1eFaoVink4dv",
	"MDYOYEWUh8gNpv7wucIORPBZc81vsyK3uWR2tErGlGID9/yVUlLtUh7LBLdJ3XtRS2qKWrMu1lC51bjP",
	"uY6v6+y1b/qbdcZNVHcudX0NF8lFR/oc3PTdu32me89K4gON6ggVhHCESnMpIILnjVaj5dDJDAXLOESw",
	"12g19iCEjJmeR+ZYX82ki15YDjkzXIpXCUTwNZrV3PzEMyl02daLVqvkXBgU/irLsj6P/eXmG+1QLDfl",
	"vjPXu0N3FCRY9lt2SL/Sgv6hguZ0Zk8DmlNB53RGE5rbU/DhHZb3zb1Q3gSuVF0dkt/sCU3pA82oCOiS",
	"FgF9pIIu7Tta2Pd2HNBsDbVMkEldQ/dLhczgUvilOlCbfZkMHq2L1Vptys+oHEc7I37+aGU3l+SWcVIR",
	"2LF9T5c0sSc0d4Se0YI+UEF/04WbMBVPOuFc4I8ZxgaTAKuYEHSepkwNHPY/aEEfHW6a05QmAU13Efv/",
	"Z1c165yJdXVpM5XwD1zm1WI2h9WpzZPRtVv6uiffVmPdH7xK/IorlqJB5ZIPt5r5rocBTwLZCUwPg6pA",
	"YGSg0CiOR+g/GxB5o4AQBEvdIq6RwLZwwiv8bnvcwQN9485a3mzy/zUAurBj+/M1Y68sYlp51TFN7U80",
	"dXftMS3sOzveltfvD894P6k1Ve55qbepb3PxScrtdg/7c21a9pTOl98B52Wz/6CCp5TwX67sM/fjkdkT",
	"unDHOU0Ce0yFw+8+aNONnh5B2788hKF6VY9G/wYAAP//HFTmo7ELAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
