version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: 1
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql


  app:
    image: cr.yandex/crp6prgfic4t20er8gcr/pgstart:1c372b3c022ed72fba041ef5595fe240b0856e77
    ports:
      - "8080:8080"
    environment:
      PGPASSWORD: 1
    depends_on:
      - db
    command: >
       sh -c "sleep 10 && cd home && ls && psql -h db -U postgres -d postgres -f /docker-entrypoint-initdb.d/schema.sql && ./myServer"
#      sh -c "sleep 10 && ./app/server"
#     sh -c "sleep 10 && psql -h db -U postgres -d postgres -f /docker-entrypoint-initdb.d/schema.sql && ./server"

volumes:
  postgres_data:
