name: Go

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -o commandServer ./server/server

#      - name: Test
#        run: make test