name: CID

on: [push, pull_request]

env:
  CR_REGISTRY: crp6prgfic4t20er8gcr
  CR_REPOSITORY: myRepo
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -o commandServer ./server

      - name: Test
        run: make test

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: Install dependencies
        run: go mod download

      - name: Test
        run: make test

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs:
      - build
      - test

    steps:
      - name: Check out source code
        uses: actions/checkout@v3

      - name: Yandex Cloud CR "Login" Action for GitHub Actions
        id: login-cr
        uses: yc-actions/yc-cr-login@v1
        with:
          yc-sa-json-credentials: ${{ secrets.IAM_TOKEN }}

      - name: Build, tag, and push image to Yandex Cloud Container Registry
        run: |
          docker build -t cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
          docker push cr.yandex/$CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
          
          
          
